-- ALTER WAREHOUSE SECTION2_DATALOADING_WH RESUME;
-- We don't need to resume the warehouse even if it is suspended, it will automatically resume when needed for the exection.

USE WAREHOUSE SECTION2_DATALOADING_WH; 
USE DATABASE SECTION2_DATALOADING_DB;
USE SCHEMA SECTION2_DATALOADING_SH; 

-- SELECT * FROM SECTION2_DATALOADING_DB.INFORMATION_SCHEMA.TABLE_STORAGE_METRICS;


SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS;

ALTER WAREHOUSE SECTION2_DATALOADING_WH SUSPEND;