USE WAREHOUSE SECTION3_STAGE_WH;
USE DATABASE SECTION3_STAGE_DB;
USE SCHEMA SECTION3_STAGE_SH;

CREATE OR REPLACE FILE FORMAT NEWCSVFILEFORMAT
    TYPE=CSV
    -- FIELD_DELIMITER=',' -- Default for CSV, you can see that in the DESC Command in next command.
    SKIP_HEADER=1; -- DEFAULT IS 0

DESC FILE FORMAT NEWCSVFILEFORMAT;

CREATE OR REPLACE STAGE NEWFILEFORMATSTAGE
    URL='s3://shidhin-snowflakepublicbucket.blocked/'
    FILE_FORMAT=(FORMAT_NAME=NEWCSVFILEFORMAT);

TRUNCATE TABLE SECTION2_DATALOADING_DB.SECTION2_DATALOADING_SH.SECTION2_DATALOADING_TABLE_JPMORGAN;

SELECT * FROM SECTION2_DATALOADING_DB.SECTION2_DATALOADING_SH.SECTION2_DATALOADING_TABLE_JPMORGAN;

COPY INTO SECTION2_DATALOADING_DB.SECTION2_DATALOADING_SH.SECTION2_DATALOADING_TABLE_JPMORGAN 
    FROM @NEWFILEFORMATSTAGE
    PATTERN='.*JPMorgan.*';

SELECT * FROM SECTION2_DATALOADING_DB.SECTION2_DATALOADING_SH.SECTION2_DATALOADING_TABLE_JPMORGAN;

ALTER WAREHOUSE SECTION3_STAGE_WH SUSPEND;
    
