USE WAREHOUSE SECTION3_STAGE_WH; 
USE DATABASE SECTION3_STAGE_DB; 
USE SCHEMA SECTION3_STAGE_SH; 

CREATE OR REPLACE FILE FORMAT VALIDATIONFILEFORMAT
    TYPE=CSV 
    SKIP_HEADER=1;

CREATE OR REPLACE STAGE VALIDATIONSTAGE
    URL= 's3://shidhin-snowflakepublicbucket.blocked/'
    FILE_FORMAT=(FORMAT_NAME=VALIDATIONFILEFORMAT);

LIST @VALIDATIONSTAGE;

TRUNCATE TABLE SECTION2_DATALOADING_DB.SECTION2_DATALOADING_SH.SECTION2_DATALOADING_TABLE_JPMORGAN;

COPY INTO SECTION2_DATALOADING_DB.SECTION2_DATALOADING_SH.SECTION2_DATALOADING_TABLE_JPMORGAN 
    FROM @VALIDATIONSTAGE
    FILES=('titanic.csv')
    VALIDATION_MODE=RETURN_ERRORS;


ALTER WAREHOUSE SECTION3_STAGE_WH SUSPEND;
