USE WAREHOUSE SECTION3_STAGE_WH;
USE DATABASE SECTION3_STAGE_DB;
USE SCHEMA SECTION3_STAGE_SH; 

CREATE OR REPLACE STAGE EXTERNALACCESSINGSTAGE
    URL= 's3://shidhin-snowflakepublicbucket.blocked/'
    FILE_FORMAT=(TYPE=CSV FIELD_DELIMITER=',' SKIP_HEADER=1);

LIST @EXTERNALACCESSINGSTAGE;

-- Using already created table by deleting all the datas.
TRUNCATE TABLE SECTION2_DATALOADING_DB.SECTION2_DATALOADING_SH.SECTION2_DATALOADING_TABLE_JPMORGAN;

SELECT * FROM SECTION2_DATALOADING_DB.SECTION2_DATALOADING_SH.SECTION2_DATALOADING_TABLE_JPMORGAN;

COPY INTO SECTION2_DATALOADING_DB.SECTION2_DATALOADING_SH.SECTION2_DATALOADING_TABLE_JPMORGAN 
    FROM @EXTERNALACCESSINGSTAGE
    -- FILES=('JPMorgan.csv');
    PATTERN='.*JPMorgan.*'; -- This is case sensitive. 

SELECT * FROM SECTION2_DATALOADING_DB.SECTION2_DATALOADING_SH.SECTION2_DATALOADING_TABLE_JPMORGAN;

ALTER WAREHOUSE SECTION3_STAGE_WH SUSPEND;