CREATE OR REPLACE WAREHOUSE SECTION3_STAGE_WH;
CREATE OR REPLACE DATABASE SECTION3_STAGE_DB;
CREATE OR REPLACE SCHEMA SECTION3_STAGE_SH; 

USE WAREHOUSE SECTION3_STAGE_WH; 
USE DATABASE SECTION3_STAGE_DB;
USE SCHEMA SECTION3_STAGE_SH;

SHOW STAGES;

CREATE OR REPLACE STAGE INITIALSTAGE
    URL='s3://shidhin-snowflakepublicbucket.blocked/';

SHOW STAGES;

LIST @INITIALSTAGE;

ALTER WAREHOUSE SECTION3_STAGE_WH SUSPEND;