USE WAREHOUSE SECTION3_STAGE_WH; 
USE DATABASE SECTION3_STAGE_DB;
USE SCHEMA SECTION3_STAGE_SH;

CREATE TABLE NEWTABLEFORINSERTING(
    ID INT, 
    NAME STRING, 
    AGE INT, 
    COURSE VARCHAR(3) -- CAN BE LESS THAN 3, BUT NOT GREATER THAN 3
);

SELECT * FROM NEWTABLEFORINSERTING;

INSERT INTO NEWTABLEFORINSERTING 
VALUES (0, 'YOURNAME', 5, 'CSE');

UPDATE NEWTABLEFORINSERTING SET COURSE='IT' WHERE COURSE='CSE';

-- Can Specify to Insert only for the specif fields
INSERT INTO NEWTABLEFORINSERTING(ID, COURSE)
    VALUES 
    (2, 'MEC'),
    (3, 'CSE');

SELECT * FROM NEWTABLEFORINSERTING;

INSERT OVERWRITE INTO NEWTABLEFORINSERTING(ID, COURSE)
    VALUES 
    (1, 'CSE'),
    (2, 'MEC'),
    (3, 'IT');

DROP TABLE NEWTABLEFORINSERTING;

ALTER WAREHOUSE SECTION3_STAGE_WH SUSPEND;
